### ISSUE TITLE
After re-login cart don't work

### ISSUE THREAD

**Issue by amadin** [tenplus1/boost_cart#1]
Hi. If you used cart, then exited from cart, and then re-connect to server - then cart will don't move, even if you in it. I created issue to SmallJoker 12 days ago but it not fix this yet, maybe you will fix this because your mod have this bug too.

**Comment by tenplus1** [comment]
Carts work fine when I do what you mentioned.

**Comment by amadin** [comment]
Did you test on 0.4.13 stable?

**Comment by tenplus1** [comment]
Yep, 0.4.13 stable and daily builds...  I can re-enter cart without a problem and after 10 seconds of being empty will drop as an item.

**Comment by tchncs** [comment]
I had it also, server on latest commit and with both mods... .
