### ISSUE TITLE
Propose change player:set_eye_offset to y = -2

### ISSUE THREAD

**Issue by amadin** [tenplus1/boost_cart#3]
In functions.lua now set
```
player:set_attach(obj, "", {x=0, y=6, z=0}, {x=0, y=0, z=0})
player:set_eye_offset({x=0, y=-4, z=0},{x=0, y=-4, z=0})
```
but if player goes in the cart down then he did not see in front of you (see screenshot)

![screenshot_20160615_092338](https://cloud.githubusercontent.com/assets/13412191/16074005/32b04fa8-32f1-11e6-9eab-277917f38720.png)
so i propose change player:set_eye_offset to 
`player:set_eye_offset({x=0, y=-2, z=0},{x=0, y=-2, z=0})` (see screenshot)

![screenshot_20160615_092912](https://cloud.githubusercontent.com/assets/13412191/16074113/ae7c0f0a-32f1-11e6-9d20-bc61d02e7e56.png)

because my rollercoaster on Xanadu lose all meaning with current player:set_eye_offset, also 
the player will all still fit in the height of 2 blocks. Sorry but I saw this problem just then build rollercoaster after previous issue request.

**Comment by tenplus1** [comment]
Fixed :)
